version: "3.9"
services:
  jellyfin:
    image: ghcr.io/tminaorg/jellyfin-ffmpegof:latest
    environment:
      # - TZ=Europe/Berlin
      # - FFMPEGOF_DATABASE_TYPE=postgres
      # - FFMPEGOF_DATABASE_HOST=localhost
      # - FFMPEGOF_DATABASE_PORT=5432
      # - FFMPEGOF_DATABASE_NAME=ffmpegof
      # - FFMPEGOF_DATABASE_USERNAME=postgres
      # - FFMPEGOF_DATABASE_PASSWORD=supersecurepassword
    ports:
      - ${JELLYFIN_LAN_ONLY_IP:-}:8096:8096 # public should access via reverse proxy
    volumes:
      - jellyfin-conf:/config:Z
      - jellyfin-cache:/config/cache:z
      - jellyfin-transcodes:/config/transcodes:z
      - jellyfin-subtitles:/config/data/subtitles:z
      - /var/storage/media:/var/storage/media:ro # optional media folder, usually readonly is enough
    restart: always
  nfs-server:
    image: ghcr.io/obeone/nfs-server:latest
    cap_add:
      - SYS_ADMIN
    environment:
      # - TZ=Europe/Berlin
      - NFS_EXPORT_0=/config/cache           *(rw,sync,no_subtree_check,no_root_squash)
      - NFS_EXPORT_1=/config/transcodes      *(rw,sync,no_subtree_check,no_root_squash)
      - NFS_EXPORT_2=/config/data/subtitles  *(rw,sync,no_subtree_check,no_root_squash)
      - NFS_EXPORT_3=/var/storage/media      *(rw,sync,no_subtree_check,no_root_squash) # optional media folder
    ports:
      - ${JELLYFIN_LAN_ONLY_IP:-}:2049:2049
    volumes:
      - jellyfin-cache:/config/cache:z
      - jellyfin-transcodes:/config/transcodes:z
      - jellyfin-subtitles:/config/data/subtitles:z
      - /var/storage/media:/var/storage/media:ro # optional media folder, readonly is ideal since workers only read files and transcode them to other dirs
    restart: always
volumes:
  jellyfin-conf:
  jellyfin-cache:
  jellyfin-transcodes:
  jellyfin-subtitles:
