name: Build

on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  JELLYFIN_RFFMPEG_IMAGE_NAME: ${{ github.repository_owner }}/jellyfin-rffmpeg
  JELLYFIN_RFFMPEG_INTRO_SKIPPER_IMAGE_NAME: ${{ github.repository_owner }}/jellyfin-rffmpeg-intro-skipper

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.0.2'

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract jellyfin-rffmpeg Docker metadata
        id: meta-jellyfin-rffmpeg
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.JELLYFIN_RFFMPEG_IMAGE_NAME }}

      - name: Extract jellyfin-rffmpeg-intro-skipper Docker metadata
        id: meta-jellyfin-rffmpeg-intro-skipper
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.JELLYFIN_RFFMPEG_INTRO_SKIPPER_IMAGE_NAME }}

      # Dependencies
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
          version: latest

      - name: goreleaser info
        run: goreleaser -v

      - name: task
        uses: arduino/setup-task@v1

      - name: task info
        run: task --version

      - name: qemu
        if: github.event.pull_request.head.repo.fork == false
        uses: docker/setup-qemu-action@v2

      - name: buildx
        if: github.event.pull_request.head.repo.fork == false
        uses: docker/setup-buildx-action@v2

      # Checkout
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup go
      - name: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3

      - name: go info
        run: |
          go version
          go env

      # Cache
      - name: cache-go
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache-mod

      - name: cache-task
        uses: actions/cache@v3
        with:
          path: .task/**/*
          key: ${{ runner.os }}-go-task

      # Vendor
      - name: vendor
        run: |
          task vendor

      # Test
      #- name: tests
      #  run: |
      #    task test

      # Git status
      - name: git status
        run: git status

      # Build
      - name: build
        if: startsWith(github.ref, 'refs/tags/') == false
        run: |
          task snapshot

      # Publish
      - name: publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          task publish

      # Artifacts
      - name: artifact_linux
        uses: actions/upload-artifact@v3
        with:
          name: build_linux
          path: dist/*linux*

      - name: artifact_darwin
        uses: actions/upload-artifact@v3
        with:
          name: build_darwin
          path: dist/*darwin*
      
      - name: artifact_windows
        uses: actions/upload-artifact@v3
        with:
          name: build_windows
          path: dist/*windows*
      
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: build and push jellyfin-rffmpeg docker image
        id: build-and-push-jellyfin-rffmpeg
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/jellyfin-rffmpeg/Dockerfile
          platforms: linux/amd64/v1,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-jellyfin-rffmpeg.outputs.tags }}
          labels: ${{ steps.meta-jellyfin-rffmpeg.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: build and push jellyfin-rffmpeg-intro-skipper docker image
        id: build-and-push-jellyfin-rffmpeg-intro-skipper
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/jellyfin-rffmpeg-intro-skipper/Dockerfile
          platforms: linux/amd64/v1,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-jellyfin-rffmpeg-intro-skipper.outputs.tags }}
          labels: ${{ steps.meta-jellyfin-rffmpeg-intro-skipper.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Cleanup
      - name: cleanup
        if: github.event.pull_request.head.repo.fork == false
        run: |
          rm -f ${HOME}/.docker/config.json